version: '3.8'

services:
  db:
    image: postgres:17
    container_name: otp_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: otp_project
    ports:
      - "5432:5432"
    volumes:
      - otp_db_data:/var/lib/postgresql/data

  backend:
    build: ./Backend
    image: jarkkok1/project:latest
    container_name: otp_backend
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/otp_project
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db
  frontend:
    build: ./Frontend
    image: jarkkok1/project-frontend:latest
    container_name: otp_frontend
    depends_on:
      - backend
    environment:
      BACKEND_URL: http://backend:8080

volumes:
  otp_db_data:
