version: '3.8'

services:
  db:
    image: postgres:17
    container_name: otp_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: otp_project
    ports:
      - "5432:5432"
    volumes:
      - otp_db_data:/var/lib/postgresql/data

  backend:
    build: ./Backend
    container_name: otp_backend
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/otp_project
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db

volumes:
  otp_db_data:
