version: "3.8"

networks:
  otp_network:
    driver: bridge

volumes:
  otp_db_data:

services:
  db:
    image: postgres:17
    container_name: otp_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: otp1-project
    ports:
      - "5432:5432"
    volumes:
      - otp_db_data:/var/lib/postgresql/data
    networks:
      - otp_network
    restart: no

  backend:
    build: ./Backend
    container_name: otp_backend
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/otp1-project
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_ADDRESS: 0.0.0.0
      SERVER_PORT: 8081
      SPRING_SESSION_JDBC_INITIALIZE_SCHEMA: always
    depends_on:
      - db
    networks:
      - otp_network
    restart: no

  frontend:
    build: ./Frontend
    container_name: otp_frontend
    depends_on:
      - backend
    environment:
      BACKEND_URL: http://backend:8081
    networks:
      - otp_network
    restart: no
