### GET -- kaikki kontaktit
GET http://localhost:8080/api/contacts/user/7
Accept: application/json


### GET -- yksittäinen kontakti
GET http://localhost:8080/api/contacts/user/7/contact/1
Accept: application/json

### POST -- uusi kontakti
POST http://localhost:8080/api/contacts/add?userId=7&contactUserId=3
Content-Type: application/json

### POST -- hyväksytään kontakti
POST http://localhost:8080/api/contacts/accept?userId=3&contactUserId=7
Content-Type: application/json
