### GET -- kaikki kontaktit
GET http://localhost:8080/api/contacts/user/7
Accept: application/json

### GET -- yksittäinen kontakti
GET http://localhost:8080/api/contacts/user/4/contact/7
Accept: application/json

### GET -- kaikki tulleet ja odottavat / pending kontaktipyynnöt
GET http://localhost:8080/api/contacts/user/9/pending
Accept: application/json

### GET -- kaikki lähetetyt odottavat / pending kontaktipyynnöt
GET http://localhost:8080/api/contacts/user/9/sent
Accept: application/json

### POST -- uusi kontakti
POST http://localhost:8080/api/contacts/add?userId=7&contactUserId=9
Content-Type: application/json

### POST -- hyväksytään kontakti
POST http://localhost:8080/api/contacts/accept?userId=9&contactUserId=7
Content-Type: application/json

### DELETE -- poistetaan kontakti
DELETE http://localhost:8080/api/contacts?userId=7&contactUserId=9
Content-Type: application/json
