### GET -- kaikki kontaktit
GET http://localhost:8081/api/contacts/user/1
Accept: application/json

### GET -- yksittäinen kontakti
GET http://localhost:8081/api/contacts/user/1/contact/2
Accept: application/json

### GET -- kaikki tulleet ja odottavat / pending kontaktipyynnöt
GET http://localhost:8081/api/contacts/user/2/pending
Accept: application/json

### GET -- kaikki lähetetyt odottavat / pending kontaktipyynnöt
GET http://localhost:8081/api/contacts/user/1/sent
Accept: application/json

### POST -- uusi kontakti
POST http://localhost:8081/api/contacts/add?userId=1&contactUserId=2
Content-Type: application/json

### POST -- hyväksytään kontakti
POST http://localhost:8081/api/contacts/accept?userId=1&contactUserId=2
Content-Type: application/json

### DELETE -- poistetaan kontakti
DELETE http://localhost:8081/api/contacts?userId=1&contactUserId=2
Content-Type: application/json
