### GET -- keskustelujen viestit
GET http://localhost:8080/api/conversations/1/messages
Content-Type: application/json

### GET -- haluttu viesti keskustelusta
GET http://localhost:8080/api/conversations/1/messages/2
Content-Type: application/json

#### POST TESTI -- viestin lähetys
@conversationId = 5
POST http://localhost:8080/api/conversations/{{conversationId}}/messages
Content-Type: application/json

{
  "senderId": 1,
  "text": "katsotaas"
}

### PUT -- viestin muokkaus
PUT http://localhost:8080/api/conversations/5/messages/6
Content-Type: application/json

{
  "text": "muokkaus"
}

### DELETE -- viestin poisto
DELETE http://localhost:8080/api/conversations/5/messages/3?userId=2
Content-Type: application/json
