### GET -- kaikki käyttäjät
GET http://localhost:8080/api/users
Content-Type: application/json

### GET -- yksittäinen käyttäjä id:llä
GET http://localhost:8080/api/users/1
Content-Type: application/json

### testataan uusi rekisteröityminen
POST http://localhost:8080/api/users/register
Content-Type: application/json

{
  "username": "bob",
  "password": "12345",
  "email": "pena@example.com"
}

### Testataan login
POST http://localhost:8080/api/users/login
Content-Type: application/json

{
  "username": "bob",
  "password": "12345"
}

### Testataan profile picture
POST http://localhost:8080/api/users/1/profile-picture
Content-Type: multipart/form-data
Accept: application/json

file=@C:\Users\karki\Desktop\kuvat\tonninseteli.jpg


### Get by username

GET http://localhost:8080/api/users/username/onni123